# Generated by Django 4.1.3 on 2022-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('INR', 'INR')], default='EUR', max_length=500),
        ),
    ]
